### ISSUE TITLE
Data values for Fish

### ISSUE THREAD

**Issue by GalacticArcanum** [elsiff/MoreFish#16]
Hello

WORKS: Minecraft:Fish
DOESNT WORK: Minecraft:Fish|1
DOESNT WORK: Minecraft:Fish|2
DOESNT WORK: Minecraft:Fish|3

Spigot 12.2.2 latest version of your plugin

**Comment by mcmonkey4eva** [comment]
If using the format

```
    icon:
      id: "minecraft:fish"
      amount: 1
      durability: 0
```

As on https://github.com/elsiff/MoreFish/wiki/Custom-Fish-Tutorial

You should set the `durability` value to 1, 2, or 3 as needed.
