### ISSUE TITLE
MCMMO overrides MoreFish Drops

### ISSUE THREAD

**Issue by BlackBeltPanda** [elsiff/MoreFish#5]
It seems some Materials don't work as Icons. For example, I tried "minecraft:ironhorsearmor", "minecraft:iron_horse_armor", and "minecraft:horsearmoriron" but none of them seem to work as the fish itself never drops. No errors are thrown when the fish is caught.

**Comment by woodyn1002** [comment]
Does it happen without any other plugins? (especially McMMO)

**Comment by BlackBeltPanda** [comment]
It happens with MCMMO fishing disabled but I'll test without other plugins here in a few.

**Comment by BlackBeltPanda** [comment]
Okay, I think I figured out what's going on. With MCMMO's Fishing Drops disabled, only RAW_FISH are ever dropped. So when running MCMMO, you have to use these settings for Fishing in it's config.yml file:
```
    Fishing:  
        Level_Cap: 0  
        Drops_Enabled: true  
        Override_Vanilla_Treasures: false  
        # Always catch fish, even when treasure is found  
        Extra_Fish: true
```

Drops_Enabled needs to be true to prevent MCMMO from forcing RAW_FISH to drop.
Override_Vanilla_Treasures needs to be false to prevent MCMMO from forcing RAW_FISH to drop.
Extra_Fish may need to be true, not entirely sure; seemed to work for me either way.
